group/models.py
from otree.api import (
	models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
	Currency as c, currency_range
)

import random

author = 'Your name here'

doc = """
Your app description
"""


class Constants(BaseConstants):
	name_in_url = 'group'
	players_per_group = None
	num_rounds = 1

	category_names = ['sehr konservativ', 'sicherheitsorientiert', 'ausgeglichen', 'wachstumsorientiert', 'offensiv']

	endowment_principals = c(10)

	# Fixed Compensation
	fixed_payment = c(5)

	#Variable Compensation
	variable_payment = c(5)			# Fixer Anteil für die Agenten
	share_result = 25
	share_profit = 35


class Subsession(BaseSubsession):

	def creating_session(self):
		random_number = random.randint(1,2)
		player_list = self.get_players()
		for player in player_list:
			player.compensation = self.session.config["compensation"]
			player.participation_fee = self.session.config["participation_fee"]
			player.random_number = random_number
	
	def set_groups(self):

		# Create category lists

		cat_lists = dict.fromkeys(Constants.category_names)
		for element in cat_lists:
			cat_lists[element] = []

		# sort players into category lists by their choices
		for player in self.get_players():
			for cat_name in cat_lists:
				if player.category == cat_name:
					cat_lists[cat_name].append(player)
					

		total_players = len(self.get_players())
		group_size = 6
		number_groups = int(total_players / group_size)

		print(cat_lists)

		groups = [[] for i in range(number_groups)]
		temp = []
		for i in range(len(Constants.category_names)):
			for j in range(len(cat_lists[Constants.category_names[i]])):
				temp.append(cat_lists[Constants.category_names[i]][j])
		
		print(temp)
		for i in range(number_groups):
			print(temp[i::number_groups])
			groups[i].append(temp[i::number_groups])

		print([l[0] for l in groups])
		matrix = [l[0] for l in groups]

		# matrix = [[2, 1], [4,3]]


		self.set_group_matrix(matrix)

		print(self.get_group_matrix())

		group_matrix = self.get_group_matrix()
		for group in group_matrix:
			for player in group:
				player.my_group_id = group_matrix.index(group) + 1


	def communicate_categories(self):
		for group in self.get_groups():
			for player in group.get_players():
				player.find_principals()
				player.find_partners()
				player.get_category()


class Group(BaseGroup):
	
	def after_investments(self):
		#self.investment_success = (random.random() <= 1/3)
		for player in self.get_players():
			player.get_investment()
			player.calculate_payoffs_principals()
			player.get_outcome_of_principal()


	def after_results_principals(self):
		for player in self.get_players():
			player.get_invested_amount()
			player.get_msg_payoff_profit()
			player.calculate_payoffs_agents()


class Player(BasePlayer):

	my_group_id = models.IntegerField()

	random_number = models.IntegerField()

	compensation = models.CharField(
		doc="Compensation scheme put in place for agents (see Settings)."
		)

	participation_fee = models.CurrencyField(
		doc="Participation fee for all agents."
		)



	# Gerade Nummern sind Prinzipale und ungerade Agenten
	def role(self):
		return "Principal" if self.id_in_group % 2 == 0 else "Agent"


# Assign partners (i.e. build principal agent couples: 1-2, 3-4, 5-6)

	partner = models.IntegerField(
		doc="Gives the ID in Group of the partner.")

	def find_partners(self):
		if self.id_in_group == 1:
			self.partner = 2
		elif self.id_in_group == 2:
			self.partner = 1
		elif self.id_in_group == 3:
			self.partner = 4
		elif self.id_in_group == 4:
			self.partner = 3
		elif self.id_in_group == 5:
			self.partner = 6
		elif self.id_in_group == 6:
			self.partner = 5



# Everyone chooses the category:

	category = models.CharField(
		choices=Constants.category_names,
		widget=widgets.RadioSelect(),
		verbose_name="Bitte wählen Sie nun einen der fünf Begriffe:",
		doc="Principals choose the category which is communicated to their agent"
		)


	category_from_principal = models.CharField(
		doc="Category that agents receive from their principals indicating how they want their agent to invest. Only for the agent who is payoff relevant."
		)


	def get_category(self):
		if self.role() == "Agent":
			principal = self.get_others_in_group()[int(self.partner)-2]
			self.category_from_principal = principal.category



# Part II: Investment for Group members
	
	c_principal_1 = models.CharField()
	c_principal_2 = models.CharField()
	c_principal_3 = models.CharField()
	c_principal_4 = models.CharField()
	c_principal_5 = models.CharField()

	def find_principals(self):

		# c for corresponding
		if self.id_in_group == 1:
			self.c_principal_1 = 2
			self.c_principal_2 = 3
			self.c_principal_3 = 4
			self.c_principal_4 = 5
			self.c_principal_5 = 6
		elif self.id_in_group == 2:
			self.c_principal_1 = 1
			self.c_principal_2 = 3
			self.c_principal_3 = 4
			self.c_principal_4 = 5
			self.c_principal_5 = 6
		elif self.id_in_group == 3:
			self.c_principal_1 = 1
			self.c_principal_2 = 2
			self.c_principal_3 = 4
			self.c_principal_4 = 5
			self.c_principal_5 = 6
		elif self.id_in_group == 4:
			self.c_principal_1 = 1
			self.c_principal_2 = 2
			self.c_principal_3 = 3
			self.c_principal_4 = 5
			self.c_principal_5 = 6
		elif self.id_in_group == 5:
			self.c_principal_1 = 1
			self.c_principal_2 = 2
			self.c_principal_3 = 3
			self.c_principal_4 = 4
			self.c_principal_5 = 6
		elif self.id_in_group == 6:
			self.c_principal_1 = 1
			self.c_principal_2 = 2
			self.c_principal_3 = 3
			self.c_principal_4 = 4
			self.c_principal_5 = 5


	decision_for_p1 = models.CurrencyField(
		min=0,
		max=Constants.endowment_principals,
		widget=widgets.Slider(),					# Neuer Slider von Christian
		verbose_name="Ihre Investitionsentscheidung für Ihren Kunden:",
		doc="Agents investment for the principal in the risky asset."
		)
		
	decision_for_p2 = models.CurrencyField(
		min=0,
		max=Constants.endowment_principals,
		widget=widgets.Slider(),					# Neuer Slider von Christian
		verbose_name="Ihre Investitionsentscheidung für Ihren Kunden:",
		doc="Agents investment for the principal in the risky asset."
		)

	decision_for_p3 = models.CurrencyField(
		min=0,
		max=Constants.endowment_principals,
		widget=widgets.Slider(),					# Neuer Slider von Christian
		verbose_name="Ihre Investitionsentscheidung für Ihren Kunden:",
		doc="Agents investment for the principal in the risky asset."
		)

	decision_for_p4 = models.CurrencyField(
		min=0,
		max=Constants.endowment_principals,
		widget=widgets.Slider(),					# Neuer Slider von Christian
		verbose_name="Ihre Investitionsentscheidung für Ihren Kunden:",
		doc="Agents investment for the principal in the risky asset."
		)

	decision_for_p5 = models.CurrencyField(
		min=0,
		max=Constants.endowment_principals,
		widget=widgets.Slider(),					# Neuer Slider von Christian
		verbose_name="Ihre Investitionsentscheidung für Ihren Kunden:",
		doc="Agents investment for the principal in the risky asset."
		)



# principals can send messages to their agents:

	message = models.CharField(
		choices=["Ich bin sehr zufrieden mit Ihrer Entscheidung", "Ich bin zufrieden mit Ihrer Entscheidung",
		"Ich bin unzufrieden mit Ihrer Entscheidung", "Ich bin sehr unzufrieden mit Ihrer Entscheidung"],
		widget=widgets.RadioSelect(),
		verbose_name="Wählen Sie dazu eine der vorgefertigten Mitteilungen aus:",
		doc="Principals choose the message to send to the agents."
		)


	message_from_principal = models.CharField(
		doc="Message that agents receive from their principals."
		)


# Payoffs:

	investment = models.CurrencyField(
		doc="Indicates for everyone the investment decision as taken by their agents."
		)

	def get_investment(self):
		if self.role() == "Principal":
			agent = self.get_others_in_group()[int(self.partner)-1]
			if self.id_in_group == 2:
				self.investment = agent.decision_for_p1
			if self.id_in_group == 4:
				self.investment = agent.decision_for_p3
			if self.id_in_group == 6:
				self.investment = agent.decision_for_p5


	# Damit die Agenten ihre Investitionen für den für die Auszahlung relevanten Prinzipal sehen:

	invested_amount = models.CurrencyField(
		doc="For agents, this gives us the investment in the risky option for their relevant principal (agents own decision).")

	def get_invested_amount(self):
		if self.role() == "Agent":
			principal = self.get_others_in_group()[int(self.partner)-2]
			self.invested_amount = principal.investment




	# Investition in risky asset: Erfolgreich oder nicht erfolgreich:
	def determine_outcome(self):
		randomizer = random.randint(1,3)
		if self.role() == "Principal":
			if randomizer == 1:
				self.investment_outcome = 1
			else:
				self.investment_outcome = 0

	investment_outcome = models.IntegerField(
		doc="Turns 1 if the investment was successful and 0 in case it was not."
		)


	# Get outcome of the principals as a variable for the agents:

	outcome_of_principal = models.IntegerField(
		doc="Message that agents receive from their principals."
		)

	def get_outcome_of_principal(self):
		if self.role() == "Agent":
			principal = self.get_others_in_group()[int(self.partner)-2]
			self.outcome_of_principal = principal.investment_outcome



	def calculate_payoffs_principals(self):
		if self.role() == "Principal":
			if self.investment_outcome == 1:
				self.payoff = self.investment * 3.5 + (Constants.endowment_principals - self.investment)
				self.profit = self.investment * 2.5
			elif self.investment_outcome == 0:
				self.payoff = Constants.endowment_principals - self.investment
				self.profit = 0


	profit = models.CurrencyField(
		doc="Gives the profit of the principal."
		)

	payoff_of_principal = models.CurrencyField(
		doc="Gives for each agent the payoff of his principal."
		)

	profit_of_principal = models.CurrencyField(
		doc="Gives for each agent the payoff of his principal."
		)


	def get_msg_payoff_profit(self):
		if self.role() == "Agent":
			principal = self.get_others_in_group()[int(self.partner)-2]

group/_builtin/__init__.py
# This file is auto-generated.
# It's used to aid autocompletion in code editors.

import otree.api
from .. import models


class Page(otree.api.Page):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

group/templates/group/Agent.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Sie treffen nun die Entscheidung als Finanzberater
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static "group/bootstrap-slider.min.css" %}"/>
    <link rel="stylesheet" href="{% static "group/category.css" %}">
    <link rel="stylesheet" href="{% static "group/agent.css" %}">
{% endblock %}

{% block scripts %}
    <script src="{% static "group/bootstrap-slider.min.js" %}"></script>
    <script type="text/javascript">
        
        $('.otree-btn-next').hide();
var touched =  {
    1: 0,
    2: 0,
    3: 0,
    4: 0,
    5: 0,
};

function check_all_sliders_touched(num_sliders) {
    sum = 0;
    for (e in touched) {
        sum += touched[e];
    }
    return (sum == num_sliders);
}

$("#id_decision_for_p1").slider();
$("#id_decision_for_p2").slider();
$("#id_decision_for_p3").slider();
$("#id_decision_for_p4").slider();
$("#id_decision_for_p5").slider();



function calc_client_payoffs(risky) {
    var safe = 10 - risky;

    var good_state = safe + risky*3.5;
    var bad_state = safe;

    return {'win': good_state, 'lose': bad_state};
}

function calc_advisor_payoffs(risky) {
    var fixed_pay = {{ Constants.fixed_payment|json }};
    var compensation = {{ player.compensation|json }};
    var share_result = {{ Constants.share_result|json }};
    var share_profit = {{ Constants.share_profit|json }};
    var client_payoffs = calc_client_payoffs(risky);

    if (compensation == 'fixed') {
        return {'win': 5, 'lose': 5, 'ev': 5};
    } else if (compensation == 'variable_result') {
        return {
            'win': fixed_pay + client_payoffs['win']*share_result/100, 
            'lose': fixed_pay + client_payoffs['lose']*share_result/100, 
        };
    } else { // variable_profit
        return {
            'win': fixed_pay + risky*2.5*share_profit/100,
            'lose': fixed_pay,
        };
    }
}

$('#id_decision_for_p1').on('change', function (event) {
    change_table(event);
});

$('.slider-handle').hide();
$('.slider').on('mousedown', function (event) {
    $(this).find('.slider-handle:not(.hide)').show();
});

$('#id_decision_for_p2').on('change', function (event) {
    change_table(event);
});

$('#id_decision_for_p3').on('change', function (event) {
    change_table(event);
});

$('#id_decision_for_p4').on('change', function (event) {
    change_table(event);
});

$('#id_decision_for_p5').on('change', function (event) {
    change_table(event);
});


function change_table(event) {
    var client_payoffs = calc_client_payoffs(event.target.value);
    var advisor_payoffs = calc_advisor_payoffs(event.target.value);

    var id = event.target.id.slice(-1);
    //console.log(id);

    touched[id] = 1;

    $('#safe_'+id).html((10 - event.target.value).toFixed(2)+'€');
    $('#risky_'+id).html(parseFloat(event.target.value).toFixed(2)+'€');

    $('#lose_'+id).html(client_payoffs['lose'].toFixed(2)+'€');
    $('#win_'+id).html(client_payoffs['win'].toFixed(2)+'€');

    $('#pay_lose_'+id).html(advisor_payoffs['lose'].toFixed(2)+'€');
    $('#pay_win_'+id).html(advisor_payoffs['win'].toFixed(2)+'€');
    //$('#pay_ev_'+id).html(advisor_payoffs['ev'].toFixed(2));

    // var ev = calc_sums();
    // $('#ev').html(ev.toFixed(2));

    if (check_all_sliders_touched(5)) {
        $('.otree-btn-next').show();
    }
}

function calc_sums() {
    var ev_sum = 0;

    for (var id = 1; id < 5; id++) {
        loss = parseFloat($('#pay_lose_'+id).html());
        win = parseFloat($('#pay_win_'+id).html());
        ev_sum += (loss * 2/3) + (win * 1/3);
    }

    return ev_sum;
}
    </script>
{% endblock %}

{% block content %}

    <p><b>Die riskante Anlage</b></p>
    <p>Mit einer Wahrscheinlichkeit von 1/3 erhält der Kunde eine Rendite von +250% auf das investierte Kapital. <br/>
    Seine Auszahlung beträgt in diesem Fall: {{ Constants.endowment_principals }} + 2,5 * Investment.
    </p>
    <p>
        Mit einer Wahrscheinlichkeit von 2/3 erhält der Kunde eine Rendite von -100% auf das investierte Kapital.<br />
        Seine Auszahlung beträgt in diesem Fall: {{ Constants.endowment_principals }} - Investment.
    </p>
    <p><b>Ihre Auszahlung</b></p>
    <p>
    {% if player.compensation == "fixed" %}

    	Als Finanzberater erhalten Sie eine feste Auszahlung von {{ Constants.fixed_payment }}. Das bedeutet, die Entscheidung, die Sie für Ihren Kunden treffen, hat keinen Einfluss auf Ihre eigene Auszahlung.

    {% elif player.compensation == "variable_result" %}

    	Als Finanzberater erhalten Sie eine feste Auszahlung von {{ Constants.fixed_payment }} und zusätzlich {{ Constants.share_result }}% vom Ergebnis Ihres Kunden. Das bedeutet, die Entscheidung, die Sie für Ihren Kunden treffen, hat auch einen Einfluss auf Ihre eigene Auszahlung.

    {% elif player.compensation == "variable_profit" %}

    	Als Finanzberater erhalten Sie eine feste Auszahlung von {{ Constants.fixed_payment }} und zusätzlich {{ Constants.share_profit }}% von der Rendite Ihres Kunden. Das bedeutet, die Entscheidung, die Sie für Ihren Kunden treffen, hat auch einen Einfluss auf Ihre eigene Auszahlung.

    {% endif %}
    </p>

    <p>Die Tabelle zeigt den Anlagewunsch jedes Ihrer Kunden. Durch Klicken auf die graue Skala und Bewegen des jeweiligen Sliders können Sie die Investition in die riskanten Anlage für jeden Kunden individuell auswählen. Daneben sehen Sie die möglichen Auszahlungen an den Kunden und Ihre eigene Beratervergütung.</p>

    <table width="100%">
        <tr>
            <th colspan="2">Kunde</th>
            <th colspan="3">Investment</th>
            <th colspan="2">Auszahlung Kunde</th>
            <th colspan="3">Auszahlung Berater</th>
        </tr>
        <tr>
            <th width="15">#</th>
            <th width="180">Anlagewunsch</th>
            <th width="60">sicher</th>
            <th width="260"></th>
            <th width="65">riskant</th>
            <th width="100">schlecht</th>
            <th width="75">gut</th>
            <th width="100">schlecht</th>
            <th width="75">gut</th>
        </tr>
        <tr>
            <td>1</td>
            <td>{{ p1_category }}</td>
            <td id="safe_1">0.00€</td>
            <td align="center"><span class="slider-label-left">0%</span><input id="id_decision_for_p1" name="decision_for_p1" type="text" data-slider-min="0" data-slider-max="10" data-slider-step="0.1" data-slider-value="0.0"/><span class="slider-label-right">100%</span></td>
            <td id="risky_1">0.00€</td>
            <td id="lose_1">0.00€</td>
            <td id="win_1">0.00€</td>
            <td id="pay_lose_1">0.00€</td>
            <td id="pay_win_1">0.00€</td>
        </tr>
        <tr>
            <td>2</td>
            <td>{{ p2_category }}</td>
            <td id="safe_2">0.00€</td>
            <td align="center"><span class="slider-label-left">0%</span><input id="id_decision_for_p2" name="decision_for_p2" type="text" data-slider-min="0" data-slider-max="10" data-slider-step="0.1" data-slider-value="0.0"/><span class="slider-label-right">100%</span></td>
            <td id="risky_2">0.00€</td>
            <td id="lose_2">0.00€</td>
            <td id="win_2">0.00€</td>
            <td id="pay_lose_2">0.00€</td>
            <td id="pay_win_2">0.00€</td>
        </tr>
        <tr>
            <td>3</td>
            <td>{{ p3_category }}</td>
            <td id="safe_3">0.00€</td>
            <td align="center"><span class="slider-label-left">0%</span><input id="id_decision_for_p3" name="decision_for_p3" type="text" data-slider-min="0" data-slider-max="10" data-slider-step="0.1" data-slider-value="0.0"/><span class="slider-label-right">100%</span></td>
            <td id="risky_3">0.00€</td>
            <td id="lose_3">0.00€</td>
            <td id="win_3">0.00€</td>
            <td id="pay_lose_3">0.00€</td>
            <td id="pay_win_3">0.00€</td>
        </tr>
        <tr>
            <td>4</td>
            <td>{{ p4_category }}</td>
            <td id="safe_4">0.00€</td>
            <td align="center"><span class="slider-label-left">0%</span><input id="id_decision_for_p4" name="decision_for_p4" type="text" data-slider-min="0" data-slider-max="10" data-slider-step="0.1" data-slider-value="0.0"/><span class="slider-label-right">100%</span></td>
            <td id="risky_4">0.00€</td>
            <td id="lose_4">0.00€</td>
            <td id="win_4">0.00€</td>
            <td id="pay_lose_4">0.00€</td>
            <td id="pay_win_4">0.00€</td>
        </tr>
        <tr>
            <td>5</td>
            <td>{{ p5_category }}</td>
            <td id="safe_5">0.00€</td>
            <td align="center"><span class="slider-label-left">0%</span><input id="id_decision_for_p5" name="decision_for_p5" type="text" data-slider-min="0" data-slider-max="10" data-slider-step="0.1" data-slider-value="0.0"/><span class="slider-label-right">100%</span></td>
            <td id="risky_5">0.00€</td>
            <td id="lose_5">0.00€</td>
            <td id="win_5">0.00€</td>
            <td id="pay_lose_5">0.00€</td>
            <td id="pay_win_5">0.00€</td>
        </tr>
    </table>
    <p>&nbsp;</p>
    <p>Zur Erinnerung: Sie selbst haben die Anlagestrategien wie folgt verteilt:</p>
    <div id="super_box">
        <div id="left_axis_label" class="axis_label">0%</div>
        <div id="right_axis_label" class="axis_label">100%</div>
        <div id="axis_box">
            <div class="category_label" id="a" style="width: {{ width_a }}px; margin-right: 0px;">
                <div class="label">sehr konservativ</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="b" style="width: {{ width_b }}px; margin-right: 0px;">
                <div class="label">sicherheitsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="c" style="width: {{ width_c }}px; margin-right: 0px;">
                <div class="label">ausgeglichten</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="d" style="width: {{ width_d }}px; margin-right: 0px;">
                <div class="label">wachstumsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="e" style="width: {{ width_e }}px; margin-right: 0px;">
                <div class="label">offensiv</div>
                <div class="category_label_handle handle_right"></div>
            </div>
        </div>
    </div>

    <p>&nbsp; </p>
    <div align="right">{% next_button %}</div>

{% endblock %}

group/templates/group/CategoryPick.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Sie treffen nun die Entscheidung als Kunde
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static "group/category.css" %}">
    <style type="text/css">
        .category_label:hover {
/*          border: 2px dashed orange; */
            color: orange;
        }

        .label {
            cursor: pointer !important;
        }

        .sel {
            /*border: 2px solid red;*/
            color: orange;
        }
    </style>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $('.otree-btn-next').hide();
        $('.category_label').on('click', function (event) {
            // console.log(event);
            $('.category_label').removeClass('sel');
            $(event.delegateTarget).addClass('sel');

            var names = {
                'a': "sehr konservativ",
                'b': "sicherheitsorientiert",
                'c': "ausgeglichen",
                'd': "wachstumsorientiert",
                'e': "offensiv",
            }

            $('#id_category').val(names[event.currentTarget.id]);
            $('.otree-btn-next').show();
        });
    </script>
{% endblock %}

{% block content %}

    <p>Bitte wählen Sie die Anlagestrategien aus, die Ihr späterer Berater für Sie umsetzen soll.</p><p>Klicken Sie dazu direkt auf die Strategie. Orange Schrift markiert Ihre Auswahl. Zur Erinnerung ist Ihre Einteilung aus Teil 1 nochmals dargestellt. Ihr Berater erfährt nur die ausgewählte Strategie. Er erfährt Ihre Einteilung nicht.</p>

    <div id="super_box">
        <div id="left_axis_label" class="axis_label">0%</div>
        <div id="right_axis_label" class="axis_label">100%</div>
        <div id="axis_box">
            <div class="category_label" id="a" style="width: {{ width_a }}px; margin-right: 0px;">
                <div class="label">sehr konservativ</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="b" style="width: {{ width_b }}px; margin-right: 0px;">
                <div class="label">sicherheitsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="c" style="width: {{ width_c }}px; margin-right: 0px;">
                <div class="label">ausgeglichen</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="d" style="width: {{ width_d }}px; margin-right: 0px;">
                <div class="label">wachstumsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="e" style="width: {{ width_e }}px; margin-right: 0px;">
                <div class="label">offensiv</div>
                <div class="category_label_handle handle_right"></div>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>

    <input type="hidden" id="id_category" name="category"/>

    <div align="right">{% next_button %}</div>

{% endblock %}

group/templates/group/Instructions1.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Teil 2 - Instruktionen (1/3)
{% endblock %}

{% block styles%}
    <style type="text/css">
        .controls label {
            margin-right: 10px;
        }
    </style>
{% endblock %}

{% block content %}
    <p>Sie beginnen nun mit dem zweiten Teil des Experiments. Wir machen Sie zunächst mit den beiden Rollen dieses Studienteils vertraut: <em>Kunden</em> und <em>Finanzberater</em>.</p>

    <p><strong>Kunden</strong></p>
    <p>Kunden besitzen {{ Constants.endowment_principals }}, die investiert werden sollen. Sie treten daher in Kontakt mit einem Finanzberater, dem sie mitteilen, wie die Anlageentscheidung für sie getroffen werden soll. Dazu wählen sie eine der fünf Anlagestrategien aus, die sie bereits in Teil 1 kennengelernt haben. Am Ende erhalten Kunden als Auszahlung das Ergebnis der für sie getroffenen Investition. Sie können ihrem Finanzberater dann eine Nachricht schicken, in der sie ihre Zufriedenheit oder Unzufriedenheit mit seiner Entscheidung ausdrücken.</p>
    
    <p><strong>Finanzberater</strong></p>
    <p>Finanzberater treffen die Investitionsentscheidung für ihre Kunden. Sie erhalten dazu von ihren Kunden eine Mitteilung, welche Anlagestrategie verfolgt  werden soll. Finanzberater sind an diese Mitteilung jedoch nicht gebunden, sondern entscheiden frei. 

    {% if player.compensation == "fixed" %}
    	Am Ende erhalten Finanzberater als Auszahlung einen fixen Betrag in Höhe von {{ Constants.fixed_payment }}.

    {% elif player.compensation == "variable_result" %}
    	Am Ende erhalten Finanzberater als Auszahlung einen fixen Betrag in Höhe von {{ Constants.fixed_payment }} und einen prozentualen Anteil am Investitionsergebnis ihrer Kunden.

    {% elif player.compensation == "variable_profit" %}
    	Am Ende erhalten Finanzberater als Auszahlung einen fixen Betrag in Höhe von {{ Constants.fixed_payment }} und einen prozentualen Anteil an der Rendite ihrer Kunden.

    {% endif %}

    Finanzberater erhalten die Nachricht zur Zufriedenheit bzw. Unzufriedenheit ihrer Kunden.</p>
    

    <p><strong>Kontrollfragen</strong></p>
    {% formfield player.question_1 label="Finanzberater entscheiden, welcher Anteil der 10 € ihrer Kunden in die riskante Anlage investiert werden soll." %}
    
    {% formfield player.question_2 label="Nachdem sie das Ergebnis erfahren haben, können Finanzberater eine Nachricht an Ihre Kunden schicken." %}
    

    <div align="right">{% next_button %}</div>

{% endblock %}

group/templates/group/MyPage.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Willkommen
{% endblock %}

{% block content %}

	blablabla.

    {% next_button %}

{% endblock %}