single/models.py
from otree.api import (
	models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
	Currency as c, currency_range
)

import random

author = 'Luisa Kling, Christian König-Kersting'

doc = """
Risk Taking for Others Experiment 2018
"""


class Constants(BaseConstants):
	name_in_url = 'single'
	players_per_group = None
	num_rounds = 1


	category_names = ['sehr konservativ', 'sicherheitsorientiert', 'ausgeglichen', 'wachstumsorientiert', 'offensiv']

	duration = 45

	endowment_principals = c(10)


	# Fixed Compensation
	fixed_payment = c(5)

	#Variable Compensation
	share_result = 25				# In Prozent
	share_profit = 35

class Subsession(BaseSubsession):

	def creating_session(self):
		random_number = random.randint(1,2)
		for player in self.get_players():
			player.compensation = self.session.config["compensation"]
			player.participation_fee = self.session.config["participation_fee"]
			player.random_number = random_number
	
	def set_groups(self):
		# Create category lists
		cat_lists = dict.fromkeys(Constants.category_names)
		for element in cat_lists:
			cat_lists[element] = []

		# sort players into category lists by their choices
		for player in self.get_players():
			for cat_name in cat_lists:
				if player.category == cat_name:
					cat_lists[cat_name].append(player)
					

		total_players = len(self.get_players())
		group_size = 2
		number_groups = int(total_players / group_size)

		# print(cat_lists)

		groups = [[] for i in range(number_groups)]
		temp = []
		for i in range(len(Constants.category_names)):
			for j in range(len(cat_lists[Constants.category_names[i]])):
				temp.append(cat_lists[Constants.category_names[i]][j])
		
		# print(temp)
		for i in range(number_groups):
			#print(temp[i::number_groups])
			groups[i].append(temp[i::number_groups])

		# CK: I am not sure what you are doing here
		# print([l[0] for l in groups])		# macht ne Klammer weniger
		matrix = [l[0] for l in groups]

		self.set_group_matrix(matrix)
		# print(self.get_group_matrix())

		# let players know which group they are in
		group_matrix = self.get_group_matrix()
		for group in group_matrix:
			for player in group:
				player.my_group_id = group_matrix.index(group) + 1


	def communicate_categories(self):
		for group in self.get_groups():
			for player in group.get_players():
				player.get_category()


class Group(BaseGroup):
	investment_success = models.BooleanField(doc="Turns true if the investment was successful and 0 in case it was not.")
	
	def after_investments(self):
		self.investment_success = (random.random() <= 1/3)
		for player in self.get_players():
			player.get_investment()
			player.calculate_payoffs_principals()

	def after_results_principals(self):
		for player in self.get_players():
			player.get_msg_payoff_profit()
			player.calculate_payoffs_agents()


class Player(BasePlayer):
	
	my_group_id = models.PositiveIntegerField(doc="Gives each player his group ID (see subsession)")

	random_number = models.IntegerField(doc="Turns either 1 or 2 (see subsession) and is used to randomly assign roles in the experiment (see def role).")

	compensation = models.CharField(doc="Compensation scheme put in place for agents (see Settings).")

	participation_fee = models.CurrencyField(doc="Participation fee for all agents (can be modified in Settings).")

	def role(self):
		return "Principal" if self.id_in_group == self.random_number else "Agent"

# Everyone chooses the category:

	category = models.CharField(
		choices=Constants.category_names,
		verbose_name="ein Berater soll mein Vermögen wie folgt für mich anlegen:",
		doc="Principals choose the category which is communicated to their agent")


	category_from_principal = models.CharField(
		doc="Category that agents receive from their principals indicating how they want their agent to invest.")


	def get_category(self):
		self.category_from_principal = self.get_others_in_group()[0].category


# Everyone takes the investment decision for their principal:

	decision_for_p1 = models.CurrencyField(
		min=0,
		max=Constants.endowment_principals,
		widget=widgets.Slider(),					# Neuer Slider von Christian
		verbose_name="Ihre Investitionsentscheidung für Ihren Kunden:",
		doc="Agents investment for the principal in the risky asset.")

	investment = models.CurrencyField(doc="Indicates for everyone the investment decision as taken by their agents.")

	def get_investment(self):
		agent = self.get_others_in_group()[0]
		self.investment = agent.decision_for_p1


# principals can send messages to their agents:

	message = models.CharField(
		choices=["Ich bin sehr zufrieden mit Ihrer Entscheidung", "Ich bin zufrieden mit Ihrer Entscheidung",
		"Ich bin unzufrieden mit Ihrer Entscheidung", "Ich bin sehr unzufrieden mit Ihrer Entscheidung"],
		widget=widgets.RadioSelect(),
		verbose_name="Wählen Sie dazu eine der vorgefertigten Mitteilungen aus:",
		doc="Principals choose the message to send to the agents.")

	message_from_principal = models.CharField(doc="Message that agents receive from their principals.")


# Payoffs:
	def calculate_payoffs_principals(self):
		if self.role() == "Principal":
			if self.group.investment_success:
				self.payoff = self.investment * 3.5 + (Constants.endowment_principals - self.investment)
				self.profit = self.investment * 2.5
			else:
				self.payoff = Constants.endowment_principals - self.investment
				self.profit = 0

	profit = models.CurrencyField(doc="Gives the profit of the principal.")

	payoff_of_principal = models.CurrencyField(doc="Gives for each agent the payoff of his principal.")


	profit_of_principal = models.CurrencyField(doc="Gives for each agent the payoff of his principal.")


	def get_msg_payoff_profit(self):
		principal = self.get_others_in_group()[0]
		self.profit_of_principal = principal.profit
		self.payoff_of_principal = principal.payoff
		self.message_from_principal = principal.message


	def calculate_payoffs_agents(self):
		if self.role() == "Agent":
			if self.compensation == "fixed":
				self.payoff = Constants.fixed_payment
			if self.compensation == "variable_result":
				self.payoff = Constants.fixed_payment + Constants.share_result/100 * self.payoff_of_principal
			if self.compensation == "variable_profit":
				self.payoff = Constants.fixed_payment + Constants.share_profit/100 * self.profit_of_principal


	# Comprehension Questions
	question_1 = models.CharField(
		widget=widgets.RadioSelectHorizontal(),
		choices=["Richtig", "Falsch"])

	question_2 = models.CharField(
		widget=widgets.RadioSelectHorizontal(),
		choices=["Richtig", "Falsch"])

	question_3 = models.CurrencyField()

	question_4 = models.CurrencyField()

	question_5 = models.CharField(
		widget=widgets.RadioSelectHorizontal(),
		choices=["Richtig", "Falsch"])

	question_6 = models.CharField(widget=widgets.RadioSelectHorizontal(), choices=["Richtig", "Falsch"])


	# Questionnaire:
	age = models.PositiveIntegerField(
		max=100,
		verbose_name="Wie alt sind Sie?",
		doc="We ask participants for their age between 0 and 100 years")

	gender = models.CharField(
		choices=["männlich", "weiblich", "anderes"],
		widget=widgets.RadioSelectHorizontal(),
		verbose_name="Was ist Ihr Geschlecht?",
		doc="gender indication")

	studies = models.CharField(
		blank=True,
		verbose_name="Was studieren Sie im Hauptfach?",
		doc="field of studies indication.")

	nonstudent = models.BooleanField(
		widget=widgets.CheckboxInput(),
		verbose_name="Kein Student",
		doc="Ticking the checkbox means that the participant is a non-student.")

	financial_advice = models.BooleanField(
		choices=[(True, "Ja"),(False, "Nein")],
		widget=widgets.RadioSelectHorizontal(),
		verbose_name="Haben Sie bereits eine Bankberatung in Anspruch genommen?",
		doc="We ask participants if they ever made use of financial advice.")

	income = models.CurrencyField(
		verbose_name="Wie viel Geld im Monat steht Ihnen frei zur Verfügung?",
		doc="We ask participants how much money they have freely available each month.")

	# fields for risk elicitation

	cat_end_rel_1 = models.FloatField(
		doc="Indicates the end point of the first category in relative size.")

	cat_end_rel_2 = models.FloatField(
		doc="Indicates the end point of the second category in relative size.")

	cat_end_rel_3 = models.FloatField(
		doc="Indicates the end point of the third category in relative size.")

	cat_end_rel_4 = models.FloatField(
		doc="Indicates the end point of the fourth category in relative size.")

	cat_end_rel_5 = models.FloatField(
		doc="Indicates the end point of the fifth category in relative size.")

	cat_end_abs_1 = models.PositiveIntegerField(
		doc="Indicates the end point of the first category in pixels.")

	cat_end_abs_2 = models.PositiveIntegerField(
		doc="Indicates the end point of the second category in pixels.")

	cat_end_abs_3 = models.PositiveIntegerField(
		doc="Indicates the end point of the third category in pixels.")

	cat_end_abs_4 = models.PositiveIntegerField(
		doc="Indicates the end point of the fourth category in pixels.")

	cat_end_abs_5 = models.PositiveIntegerField(
		doc="Indicates the end point of the fifth category in pixels.")

single/_builtin/__init__.py
# This file is auto-generated.
# It's used to aid autocompletion in code editors.

import otree.api
from .. import models


class Page(otree.api.Page):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()


class WaitPage(otree.api.WaitPage):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()


class Bot(otree.api.Bot):
    def z_autocomplete(self):
        self.subsession = models.Subsession()
        self.group = models.Group()
        self.player = models.Player()

single/templates/single/Agent.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Sie treffen nun die Entscheidung als Finanzberater
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static "single/bootstrap-slider.min.css" %}"/>
    <link rel="stylesheet" href="{% static "single/category.css" %}">
    <link rel="stylesheet" href="{% static "single/agent.css" %}">
{% endblock %}

{% block scripts %}
    <script src="{% static "single/bootstrap-slider.min.js" %}"></script>
    <script type="text/javascript">
        
        $('.otree-btn-next').hide();
var touched =  {
    1: 0,
    2: 0,
    3: 0,
    4: 0,
    5: 0,
};

function check_all_sliders_touched(num_sliders) {
    sum = 0;
    for (e in touched) {
        sum += touched[e];
    }
    return (sum == num_sliders);
}

$("#id_decision_for_p1").slider();
// $("#id_invest_client_2").slider();
// $("#id_invest_client_3").slider();
// $("#id_invest_client_4").slider();


function calc_client_payoffs(risky) {
    var safe = 10 - risky;

    var good_state = safe + risky*3.5;
    var bad_state = safe;

    return {'win': good_state, 'lose': bad_state};
}

function calc_advisor_payoffs(risky) {
    var fixed_pay = {{ Constants.fixed_payment|json }};
    var compensation = {{ player.compensation|json }};
    var share_result = {{ Constants.share_result|json }};
    var share_profit = {{ Constants.share_profit|json }};
    var client_payoffs = calc_client_payoffs(risky);

    if (compensation == 'fixed') {
        return {'win': 5, 'lose': 5, 'ev': 5};
    } else if (compensation == 'variable_result') {
        return {
            'win': fixed_pay + client_payoffs['win']*share_result/100, 
            'lose': fixed_pay + client_payoffs['lose']*share_result/100, 
        };
    } else { // variable_profit
        return {
            'win': fixed_pay + risky*2.5*share_profit/100,
            'lose': fixed_pay,
        };
    }
}

$('#id_decision_for_p1').on('change', function (event) {
    change_table(event);
});

$('.slider-handle').hide();
$('.slider').on('mousedown', function (event) {
    $(this).find('.slider-handle:not(.hide)').show();
});

// $('#id_invest_client_2').on('change', function (event) {
//     change_table(event);
// });

// $('#id_invest_client_3').on('change', function (event) {
//     change_table(event);
// });

// $('#id_invest_client_4').on('change', function (event) {
//     change_table(event);
// });

function change_table(event) {
    var client_payoffs = calc_client_payoffs(event.target.value);
    var advisor_payoffs = calc_advisor_payoffs(event.target.value);

    var id = event.target.id.slice(-1);
    //console.log(id);

    touched[id] = 1;

    $('#safe_'+id).html((10 - event.target.value).toFixed(2)+'€');
    $('#risky_'+id).html(parseFloat(event.target.value).toFixed(2)+'€');

    $('#lose_'+id).html(client_payoffs['lose'].toFixed(2)+'€');
    $('#win_'+id).html(client_payoffs['win'].toFixed(2)+'€');

    $('#pay_lose_'+id).html(advisor_payoffs['lose'].toFixed(2)+'€');
    $('#pay_win_'+id).html(advisor_payoffs['win'].toFixed(2)+'€');
    //$('#pay_ev_'+id).html(advisor_payoffs['ev'].toFixed(2));

    // var ev = calc_sums();
    // $('#ev').html(ev.toFixed(2));

    if (check_all_sliders_touched(1)) {
        $('.otree-btn-next').show();
    }
}

function calc_sums() {
    var ev_sum = 0;

    for (var id = 1; id < 5; id++) {
        loss = parseFloat($('#pay_lose_'+id).html());
        win = parseFloat($('#pay_win_'+id).html());
        ev_sum += (loss * 2/3) + (win * 1/3);
    }

    return ev_sum;
}
    </script>
{% endblock %}

{% block content %}

    <p><b>Die riskante Anlage</b></p>
    <p>Mit einer Wahrscheinlichkeit von 1/3 erhält der Kunde eine Rendite von +250% auf das investierte Kapital. <br/>
    Seine Auszahlung beträgt in diesem Fall: {{ Constants.endowment_principals }} + 2,5 * Investment.
    </p>
    <p>
        Mit einer Wahrscheinlichkeit von 2/3 erhält der Kunde eine Rendite von -100% auf das investierte Kapital.<br />
        Seine Auszahlung beträgt in diesem Fall: {{ Constants.endowment_principals }} - Investment.
    </p>
    <p><b>Ihre Auszahlung</b></p>
    <p>
    {% if player.compensation == "fixed" %}

    	Als Finanzberater erhalten Sie eine feste Auszahlung von {{ Constants.fixed_payment }}. Das bedeutet, die Entscheidung, die Sie für Ihren Kunden treffen, hat keinen Einfluss auf Ihre eigene Auszahlung.

    {% elif player.compensation == "variable_result" %}

    	Als Finanzberater erhalten Sie eine feste Auszahlung von {{ Constants.fixed_payment }} und zusätzlich {{ Constants.share_result }}% vom Ergebnis Ihres Kunden. Das bedeutet, die Entscheidung, die Sie für Ihren Kunden treffen, hat auch einen Einfluss auf Ihre eigene Auszahlung.

    {% elif player.compensation == "variable_profit" %}

    	Als Finanzberater erhalten Sie eine feste Auszahlung von {{ Constants.fixed_payment }} und zusätzlich {{ Constants.share_profit }}% vom positiven Ertrag aus der Investition. Das bedeutet, die Entscheidung, die Sie für Ihren Kunden treffen, hat auch einen Einfluss auf Ihre eigene Auszahlung.

    {% endif %}
    </p>

    <p>Die Tabelle zeigt den Anlagewunsch jedes Ihrer Kunden. Durch Klicken auf die graue Skala und Bewegen des jeweiligen Sliders können Sie die Investition in die riskanten Anlage für jeden Kunden individuell auswählen. Daneben sehen Sie die möglichen Auszahlungen an den Kunden und Ihre eigene Beratervergütung.</p>

    <table width="100%">
        <tr>
            <th colspan="2">Kunde</th>
            <th colspan="3">Investment</th>
            <th colspan="2">Auszahlung Kunde</th>
            <th colspan="3">Auszahlung Berater</th>
        </tr>
        <tr>
            <th width="15">#</th>
            <th width="180">Anlagewunsch</th>
            <th width="60">sicher</th>
            <th width="260"></th>
            <th width="65">riskant</th>
            <th width="100">schlecht</th>
            <th width="75">gut</th>
            <th width="100">schlecht</th>
            <th width="75">gut</th>
        </tr>
        <tr>
            <td>1</td>
            <td>{{ p1_category }}</td>
            <td id="safe_1">0.00€</td>
            <td align="center"><span class="slider-label-left">0%</span><input id="id_decision_for_p1" name="decision_for_p1" type="text" data-slider-min="0" data-slider-max="10" data-slider-step="0.1" data-slider-value="0.0"/><span class="slider-label-right">100%</span></td>
            <td id="risky_1">0.00€</td>
            <td id="lose_1">0.00€</td>
            <td id="win_1">0.00€</td>
            <td id="pay_lose_1">0.00€</td>
            <td id="pay_win_1">0.00€</td>
        </tr>
    </table>
    <p>&nbsp;</p>
    <p>Zur Erinnerung: Sie selbst haben die Anlagestrategien wie folgt verteilt:</p>
    <div id="super_box">
        <div id="left_axis_label" class="axis_label">0%</div>
        <div id="right_axis_label" class="axis_label">100%</div>
        <div id="axis_box">
            <div class="category_label" id="a" style="width: {{ width_a }}px; margin-right: 0px;">
                <div class="label">sehr konservativ</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="b" style="width: {{ width_b }}px; margin-right: 0px;">
                <div class="label">sicherheitsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="c" style="width: {{ width_c }}px; margin-right: 0px;">
                <div class="label">ausgeglichten</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="d" style="width: {{ width_d }}px; margin-right: 0px;">
                <div class="label">wachstumsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="e" style="width: {{ width_e }}px; margin-right: 0px;">
                <div class="label">offensiv</div>
                <div class="category_label_handle handle_right"></div>
            </div>
        </div>
    </div>

    <p>&nbsp; </p>
    <div align="right">{% next_button %}</div>

{% endblock %}

single/templates/single/CategoryElicitation.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block styles %}
    <link rel="stylesheet" href="{% static "single/jquery-ui.min.css" %}">
    <link rel="stylesheet" href="{% static "single/category.css" %}">
{% endblock %}

{% block scripts %}
    <script src="{% static "single/jquery-ui.min.js" %}"></script>
    <script src="{% static "single/category.js" %}"></script>
{% endblock %}

{% block title %}
    Teil 1
{% endblock %}

{% block content %}
    <p>Banken verwenden häufig die folgenden fünf Begriffe für verschiedene Geldanlagestrategien:</p>
    <div id="category_center_box">
        <div id="category_box">
            <div class="category_label_container">
                <div class="category_label" id="a">
                    <div class="label">sehr konservativ</div>
                    <div class="category_label_handle handle_right"></div>
                </div>
            </div>
            <div class="category_label_container">
                <div class="category_label" id="b">
                    <div class="label">sicherheitsorientiert</div>
                    <div class="category_label_handle handle_right"></div>
                </div>
            </div>
            <div class="category_label_container">
                <div class="category_label" id="c">
                    <div class="label">ausgeglichten</div>
                    <div class="category_label_handle handle_right"></div>
                </div>
            </div>
            <div class="category_label_container">
                <div class="category_label" id="d">
                    <div class="label">wachstumsorientiert</div>
                    <div class="category_label_handle handle_right"></div>
                </div>
            </div>
            <div class="category_label_container">
                <div class="category_label" id="e">
                    <div class="label">offensiv</div>
                    <div class="category_label_handle handle_right"></div>
                </div>
            </div>
        </div>
    </div>
    <p style="clear:both;">Nehmen Sie an es gäbe eine riskante Geldanlagemöglichkeit, in die ein beliebiger Teil Ihres Gesamtvermögens investiert werden kann. Der nicht investierte Teil verbleibt sicher angelegt.</p>
    <p>Die folgende Skala misst, welcher Anteil des Vermögens in die riskante Anlage investiert wird.</p>

    <div id="super_box">
        <div id="left_axis_label" class="axis_label">0%</div>
        <div id="right_axis_label" class="axis_label">100%</div>
        <div id="axis_box">
            <hr id='axis_line'> 
            <div id="axis">

            </div>
        </div>
        
    </div>

    <ul>
        <li>0% bedeutet, dass nichts in die riskante Anlage investiert wird.</li>
        <li>50% bedeutet, dass die Hälfte des Vermögens in die riskante Anlage investiert wird.</li>
        <li>100% bedeutet, dass das gesamte Vermögen in die riskante Anlage investiert wird.</li>
    </ul>


    <p>Bitte bringen Sie die fünf Strategien mit den Investitionsanteilen in die riskante Anlage in Verbindung. Ziehen Sie dazu nacheinander, beginnenend mit der ersten, die einzelnen Boxen mit der Maus auf die Skala. Im Anschluss passen Sie die Größe, d.h. den jeweils abgedeckten Investitionsbereich der einzelnen Strategien, durch Ziehen mit der Maus an den Schnittstellen der Elemente (orange hervorgehoben) an. Die Reihenfolge ist fest vorgegeben und die fünf Strategien müssen die gesamte Spanne von 0% bis 100% abdecken.</p>

    <p>Es gibt bei dieser Aufgabe keine richtigen oder falschen Anordnungen. Wir bitten Sie die Strategien so auf der Skala der möglichen Investitionsanteile zu verteilen, dass die jeweils abgedeckten Investitionsbereiche Ihrem persönlichen Verständnis der Begriffe entsprechen. </p>

    <input type="hidden" name="cat_end_rel_1" id="id_cat_end_rel_1">
    <input type="hidden" name="cat_end_rel_2" id="id_cat_end_rel_2">
    <input type="hidden" name="cat_end_rel_3" id="id_cat_end_rel_3">
    <input type="hidden" name="cat_end_rel_4" id="id_cat_end_rel_4">
    <input type="hidden" name="cat_end_rel_5" id="id_cat_end_rel_5">

    <input type="hidden" name="cat_end_abs_1" id="id_cat_end_abs_1">
    <input type="hidden" name="cat_end_abs_2" id="id_cat_end_abs_2">
    <input type="hidden" name="cat_end_abs_3" id="id_cat_end_abs_3">
    <input type="hidden" name="cat_end_abs_4" id="id_cat_end_abs_4">
    <input type="hidden" name="cat_end_abs_5" id="id_cat_end_abs_5">

    <p>Klicken Sie auf „Weiter“ um zum zweiten Teil des Experiments zu gelangen.</p>

    <div align="right">{% next_button %}</div>

{% endblock %}

single/templates/single/CategoryPick.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Sie treffen nun die Entscheidung als Kunde
{% endblock %}

{% block styles %}
    <link rel="stylesheet" href="{% static "single/category.css" %}">
    <style type="text/css">
        .category_label:hover {
/*          border: 2px dashed orange; */
            color: orange;
        }

        .label {
            cursor: pointer !important;
        }

        .sel {
            /*border: 2px solid red;*/
            color: orange;
        }
    </style>
{% endblock %}

{% block scripts %}
    <script type="text/javascript">
        $('.otree-btn-next').hide();
        $('.category_label').on('click', function (event) {
            // console.log(event);
            $('.category_label').removeClass('sel');
            $(event.delegateTarget).addClass('sel');

            var names = {
                'a': "sehr konservativ",
                'b': "sicherheitsorientiert",
                'c': "ausgeglichen",
                'd': "wachstumsorientiert",
                'e': "offensiv",
            }

            $('#id_category').val(names[event.currentTarget.id]);
            $('.otree-btn-next').show();
        });
    </script>
{% endblock %}

{% block content %}

    <p>Bitte wählen Sie die Anlagestrategien aus, die Ihr späterer Berater für Sie umsetzen soll.</p><p>Klicken Sie dazu direkt auf die Strategie. Orange Schrift markiert Ihre Auswahl. Zur Erinnerung ist Ihre Einteilung aus Teil 1 nochmals dargestellt. Ihr Berater erfährt nur die ausgewählte Strategie. Er erfährt Ihre Einteilung nicht.</p>

    <div id="super_box">
        <div id="left_axis_label" class="axis_label">0%</div>
        <div id="right_axis_label" class="axis_label">100%</div>
        <div id="axis_box">
            <div class="category_label" id="a" style="width: {{ width_a }}px; margin-right: 0px;">
                <div class="label">sehr konservativ</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="b" style="width: {{ width_b }}px; margin-right: 0px;">
                <div class="label">sicherheitsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="c" style="width: {{ width_c }}px; margin-right: 0px;">
                <div class="label">ausgeglichen</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="d" style="width: {{ width_d }}px; margin-right: 0px;">
                <div class="label">wachstumsorientiert</div>
                <div class="category_label_handle handle_right"></div>
            </div>
            <div class="category_label" id="e" style="width: {{ width_e }}px; margin-right: 0px;">
                <div class="label">offensiv</div>
                <div class="category_label_handle handle_right"></div>
            </div>
        </div>
    </div>
    <p>&nbsp;</p>

    <input type="hidden" id="id_category" name="category"/>

    <div align="right">{% next_button %}</div>

{% endblock %}

single/templates/single/Instructions2.html
{% extends "global/Page.html" %}
{% load staticfiles otree %}

{% block title %}
    Teil 2 - Instruktionen (2/3)
{% endblock %}

{% block styles%}
    <style type="text/css">
        .controls label {
            margin-right: 10px;
        }
    </style>
{% endblock %}

{% block content %}

    <p><strong>Anlagemöglichkeiten</strong><p>
    <p>Der Finanzberater entscheidet, welcher Anteil des gesamten Vermögens des Kunden in folgende riskante Anlagemöglichkeit investiert wird. Den nicht-investierten Anteil des Vermögens behält der Kunde sicher. Die riskante Anlage hat ein gutes und ein schlechtes Ergebnis:</p>

    <p>Mit einer Wahrscheinlichkeit von 1/3 erhält der Kunde eine Rendite von +250% auf das investierte Kapital. <br />
    Seine Auszahlung beträgt in diesem Fall: 10€ + 2,5 * Investment.</p>

    <p>Mit einer Wahrscheinlichkeit von 2/3 erhält der Kunde eine Rendite von -100% auf das investierte Kapital.<br />
    Seine Auszahlung beträgt in diesem Fall: 10€ - Investment.</p>

    <p><strong>Kontrollfragen</strong></p>
    {% formfield player.question_3  label="Nehmen Sie an, für einen Kunden wurden 4€ in die riskante Anlage investiert und die Investition war erfolgreich.  <br/>Welche Auszahlung erhält der Kunde?" %}

    {% formfield player.question_4  label="Nehmen Sie an, für einen Kunden wurden 6€ in die riskante Anlage investiert und die Investition war nicht erfolgreich. <br/>Welche Auszahlung erhält der Kunde?" %}

    <div align="right">{% next_button %}</div>

{% endblock %}